[versions]
kotlin = "2.0.20"
kotlinx-coroutines = "1.10.1"

[libraries]
kotlinx-coroutines-core = {group="org.jetbrains.kotlinx", name="kotlinx-coroutines-core", version.ref="kotlinx-coroutines"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
